<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto.proto

namespace GPBMetadata;

class Proto
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8d020a0b70726f746f2e70726f746f22070a05456d70747922410a0455" .
            "736572120a0a026964180120012809120c0a046e616d6518022001280912" .
            "0d0a05656d61696c18032001280912100a08706f736974696f6e18042001" .
            "280922200a08557365724c69737412140a05757365727318012003280b32" .
            "052e55736572221b0a0d55736572526571756573744964120a0a02696418" .
            "0120012809326b0a0b5573657253657276696365121f0a084c6973745573" .
            "657212062e456d7074791a092e557365724c697374220012180a06496e73" .
            "65727412052e557365721a052e55736572220012210a0644656c65746512" .
            "0e2e557365725265717565737449641a052e557365722200620670726f74" .
            "6f33"
        ), true);

        static::$is_initialized = true;
    }
}

