<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *TestReply response structure
 *
 * Generated from protobuf message <code>protos.TestReply</code>
 */
class TestReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .protos.TestReply.GetData getdataarr = 1;</code>
     */
    private $getdataarr;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Protos\TestReply\GetData[]|\Google\Protobuf\Internal\RepeatedField $getdataarr
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .protos.TestReply.GetData getdataarr = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGetdataarr()
    {
        return $this->getdataarr;
    }

    /**
     * Generated from protobuf field <code>repeated .protos.TestReply.GetData getdataarr = 1;</code>
     * @param \Protos\TestReply\GetData[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGetdataarr($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protos\TestReply\GetData::class);
        $this->getdataarr = $arr;

        return $this;
    }

}

