<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto.proto

namespace Protos;

if (false) {
    /**
     * This class is deprecated. Use Protos\TestReply\GetData instead.
     * @deprecated
     */
    class TestReply_GetData {}
}
class_exists(TestReply\GetData::class);
@trigger_error('Protos\TestReply_GetData is deprecated and will be removed in the next major release. Use Protos\TestReply\GetData instead', E_USER_DEPRECATED);

