<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto.proto

namespace GPBMetadata;

class Proto
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ada010a0b70726f746f2e70726f746f120670726f746f73221d0a0b5465" .
            "737452657175657374120e0a06747970656964180120012803225f0a0954" .
            "6573745265706c79122d0a0a6765746461746161727218012003280b3219" .
            "2e70726f746f732e546573745265706c792e476574446174611a230a0747" .
            "657444617461120a0a026964180120012803120c0a046e616d6518022001" .
            "2809323b0a045465737412330a075361795465737412132e70726f746f73" .
            "2e54657374526571756573741a112e70726f746f732e546573745265706c" .
            "792200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

